### ISSUE TITLE
Validate tracer labeling makes sense and is complete

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#436] opened 2022-05-20 19:21 UTC
### Feature Inspiration

It would be helpful if the models could validate tracer labeling to avoid entering incomplete and/or nonsensical tracer records in the database.

### Feature Description

* check if the compound is "fully labeled", and if so, the positions are optional
* check that the number of positions specified equals the number of labeled atoms
~~* check that the positions are integers between 1 and the number of labeled atoms~~

**Rob's edit - positions should be integers between 1 and the number of positions *in the compound*, not the number of labeled atoms.**  My chemistry knowledge is admittedly dated, but to the best of my recollection, positions are not relative to the element in question - they are relative to the adjoining atoms of any element above a certain mass (i.e. hydrogen isn't included in the atom positioning system).

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment] 2022-05-23 14:58
Completing #438 first would make a component of this issue simpler.

**Comment by hepcat72** [comment] 2022-06-23 22:10
#436 is a duplicate of this issue, but that one has been taken up and fleshed out more than this one, so closing.

**Closed by hepcat72** 2022-06-23 22:10 UTC
Labels: duplicate, enhancement
