### ISSUE TITLE
Search using compounds linked to PeakGroups, not PeakGroup.name

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#276] opened 2021-11-30 19:18 UTC
### Feature Inspiration

Lab members often want to refine data to specific compounds being measured, and thus it is important to be precise about the compounds. Advanced Search currently displays and searches by `PeakGroup.name` and not the linked `Compound.name`(s). Additionally, it may be useful to include Compound synonyms in the search. We also want to support a feature where a researcher can go from a Compound detail page directly to a list of PeakGroup records measuring that compound.

### Feature Description

Replace the "PeakGroup" field with "Measured Compound". Searches against this should search Compound.name and Compound.synonym. In the data table, display a list of `Compound.name`s separated by slashes `/` and linked to the compound detail page.

### Alternatives Considered

Given the [difficulties](https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/276#issuecomment-984098596) involved in implementing the above feature description, I (Rob) think we should do one of the following alternatives.

1. Keep the database as it is and require the user to enter 2 search terms (with the same value) in an `any` group that includes a search of `peak_group__compound__name` and `peak_group__compounds__synonyms__name` in order to search for any particular synonym.
2. Refactor the database to make the Synonym table contain *all* of the synonyms (either duplicating the one saved as `Compound.name` or additionally eliminating `Compound.name`) and add a priority field such that synonym name and priority are unique and priority 1 (or the lowest priority) is the primary compound name/synonym.  Then the search would only be of the synonym table.

In both cases, the column header and the values should would be as described in the original feature description above.

### Comment

none

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment] 2021-12-01 22:09
I think this proposed feature is somewhat problematic (it breaks the paradigm of an advanced search) to implement as suggested, given the way the database is structured.  The advanced search is written to enter 1 search term for 1 field, which is typical for advanced search implementations.  To have a search term search a predetermined/custom set of fields is more of a basic-search type of feature, and the data behind the advanced search is not structured to be able to specify a list of fields to search per search term field, and would be particularly difficult to graft on, given the fields are in *different* tables, meaning I would have to restructure the underlying data structure to create this customization of an otherwise generic search feature.

It would be much simpler if (I suggested this in a prior discussion about the synonyms) the synonym table contained the compound name as a duplicate of the name in Compound.name or eliminate that field entirely and add a priority integer to identify the primary compound name.

Incidentally, as was brought up in that previous discussion, the existence of Compound.name is maintained as a convenience - to make queries simpler even though it can represent multiple compounds... but as we see with this feature, maintaining the union of Compound.name and the synonyms as unique data creates a lot of overhead to maintain (functionality-wise in addition to the initial integrity concerns). The integrity issue was thought to be wholly dealt with by ensuring it was correct upon load, but as this issue demonstrates, there's more to it, because it becomes much more complex to link and search based on the compound name/synonym.  (Incidentally, linking shouldn't be an issue if the peak group ID is used in the link.)

That said, I think that the best way to deal with this for right now would be to add compound "synonym" as an additional field to search via the many-to-many relation PeakGroup has with Compound.  The user would have to compose their query using one of the 'Match any' groups and include "`compounds__name` `is` `*search-term-1*` or `compounds__synonyms__name` `is` `*search-term-2*`".  That's pretty much what's expected when it comes to an "advanced" search - you have to know what you're doing, i.e. you have to know something about the database structure.

Caveat - I'm not actually 100% sure that I can add CompoundSynonym to the PeakGroups format with the models defined as-is, given there's no key in Compound going to CompoundSynonym.  It's probably possible.  I just remember having issues when I had first tried doing the composite views in the reverse direction of the foreign keys, like I would have to do here - but I was still learning the basics of Django at the time, so maybe now I can figure it out...

**Comment by hepcat72** [comment] 2021-12-01 23:01
It's also worth noting that `PeakGroup:Compound` is a `Many:Many` relationship and `Compound:CompoundSynonym` is a `1:Many` relationship, so this will make use of the new re-filter template feature.

Initially, I wrote the customtags filter `shouldKeepManyToMany` with this caveat in the docstring:
```
    If refilter is true, this method calls the views.manyToManyFilter to filter out records that do not match search
    terms from a many-to-many related table.  Note, this can only handle composite views that contain a single many-to-
    many relationship.  If there are multiple many-to-many relationships in the composite view, a new method will have
    to be written.
```
But I just reviewed the code in preparation for this effort (because I recalled this limitation), but I had refactored the methos which originally took a single table and field during that effort to make it work with any number of M:M relationships in the composite view (by storing the data in a dictionary instead of sending it as a pair of strings) and just neglected to update that docstring.

**Comment by hepcat72** [comment] 2021-12-02 16:41
As I start to dig into this, since `PeakGroup:Compound` is `Many:Many`, I realized that it's more complicated than just joining a compound and all its synonyms with `/` (or whatever).  There are potentially multiple compounds, each with their own synonyms, so I'm not 100% sure whether different compounds and their synonyms should all be joined in the same cell on the same row... I'm going to proceed with the assumption that yes, they should all be joined together.

**Comment by hepcat72** [comment] 2021-12-02 17:17
So good news.  The reverse direction works (at least in the template - haven't tried the search yet).

I decided to join individual the union of a compound name and its synonyms with `/`, and separate (`/`-delimited) compound.name/synonyms groups with a `,` delimiter.  E.g.: `<a...>citrate/citrate-synonym-1/citrate-synonym-2</a>, <a...>isocitrate/isocitrate-synonym-1/isocitrate-synonym-2</a>`.

I don't have any synonyms yet loaded in my dev database, but here's a screenshot after adding the new column (but not removing the Peak Group column):

<img width="832" alt="Screen Shot 2021-12-02 at 11 55 41 AM" src="https://user-images.githubusercontent.com/2300532/144469408-55a2177a-3d13-47b4-8673-82cc13543dca.png">

It shows the comma delimiter.  The slash delimiter will show if/when I load some synonyms.

Incidentally, there's another complication I hadn't anticipated.  The composite views assumes that each model is linked to once in any format, as the model name is a key in the dict.  The PeakGroups format already links to Compound from Animal via its tracer foreign key, but now we want to also link to Compound from PeakGroup's many-to-many foreign relation.  This may be somewhat straightforward to implement by making the key path be the dict key and put the model name as an entry in the dict the key path points to.  But first, I'll make sure that the synonym table can be searched.

I also realized that I do not need to include this in the many-to-many re-filter mechanism since it's all included in 1 row.

**Comment by hepcat72** [comment] 2021-12-02 17:37
Huh.  I'm confused... I must be wrong about either the contents of my dev database and the decision about whether the synonym table holds/will hold a copy of the Compound.name (as a synonym).  And I'm doubly confused by the search result rendering... I just performed a search of the synonym table and expected to get no results, because I didn't think I'd had any synonyms loaded, but I did get results... yet the way I coded the rendering, it should render `Compound.name`, and if there are any synonyms, append `/CompoundSynonym.name` (which I don't see - and is why I'm surprised I got results...).

Note, I did encounter an error about a missing `synonyms` foreign key in Compound using key path `peak_group__compounds__synonyms`.  I realized I could work around that by changing the `manytomany` value in compositeviews.py to False - because that value is only used for refiltering - which isn't necessary here.  (I should change that key name to be more precise.)

**Comment by hepcat72** [comment] 2021-12-02 17:49
Yes.  I was just adding a comment WRT that.  Looking at the database in the shell, I do have a populated synonym table, and I see that I am getting results because there do exist duplicates of `Compound.name`.  In the case of `isocitrate`, there are 2 entered synonyms: `isocitrate` and `Isocitrate`. I suspect that the loop in the template is not working because of the reverse relationship...

**Comment by hepcat72** [comment] 2021-12-02 17:51
...and I'm not sure we would want to `/`-delimit values that only differ by case...

**Comment by hepcat72** [comment] 2021-12-02 17:53
Whoops.  Figured it out.  I had an mistake in my inner loop on synonyms.  Now I'm seeing `/`-delimited items...

**Comment by hepcat72** [comment] 2021-12-02 22:52
I have successfully mitigated the case issue so that only one version of multiple case variants is displayed.  I removed the redundant `Compound.name` (which is good because it works around the issue of having 2 different key paths into the compound table - and kicks that can down the road).

There was one annoying scoping issue regarding the `define` custom tag. It seems to have a drawback that I have not fully figured out. A variable defined above a loop (and set of nested loops) and updated inside the loop(s) survives iterations inside the loop, but once you get past the loop, those value changes revert to the value defined above the loop.  I implemented a work-around using a dict (which I had previously learned is more reliable to store values that persist throughout the template).

The only question I have is... should we really eliminate the `Peak Group` column?  It's usually redundant, but sometimes it's not...  Observe:

<img width="1336" alt="measuredcpd" src="https://user-images.githubusercontent.com/2300532/144515852-d1697b23-5463-4c2f-9260-9f56bebf69a9.png">

**Comment by hepcat72** [comment] 2021-12-02 23:13
Ooohhh - found (and fixed) a bug in `views.isValidQryObjPopulatedHelper`. Can't believe that wasn't encountered before...

**Comment by hepcat72** [comment] 2021-12-02 23:18
Just an aside...  I just realized that there's another `ncmp` that could be included in the list for these many:many relationships... something like "has sub-record" and "does not have sub-record" or even "has subrecords that number greater/less than", since multiple linked records are evaluated in a left-join fashion, one by one...

**Comment by hepcat72** [comment] 2021-12-02 23:21
I pushed this work onto a branch named `synonym_search`, in case anyone wants to look at this work in progress...

**Comment by hepcat72** [comment] 2021-12-02 23:22
It's pretty close to done.  Just not sure whether I should remove the Peak Group column, and if this change needs to be applied to other formats as well...  Haven't linted or run tests yet, incidentally.

**Comment by hepcat72** [comment] 2021-12-03 16:46
I also just realized that if we want to link to the Peak Group record, eliminating the Peak Group column will make that awkward... not sure how we'd do that.

**Comment by hepcat72** [comment] 2021-12-03 19:23
Wow.  Found another copy-paste-o bug.  When I'd implemented the re-filter, I copied code from the peakgroup template to the peakdata template and didn't update the record variable... SMH

**Closed** 2021-12-08 21:48 UTC
Labels: enhancement
