### ISSUE TITLE
Add Logging Module

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#445] opened 2022-06-06 21:23 UTC
NB: Would be nice to use the [logging module](https://docs.djangoproject.com/en/4.0/topics/logging/) here for some additional flexibility in output format, location, and configuration.

_Originally posted by @lparsons in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/442#discussion_r890496237_

**Comment by hepcat72** [comment] 2023-04-28 19:58
Dupe of #384

**Comment by lparsons** [comment] 2023-06-27 18:23
Duplicate of #384, closing.

**Closed by lparsons** 2023-06-27 18:23 UTC
Labels: reject:duplicate, priority:3-optional, component:8-loading
