### ISSUE TITLE
Unable to load different compounds for the same sample from separate accucor files

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#681] opened 2023-05-17 21:18 UTC
### Problem

When multiple compounds are annotated from the same sample in the same run in different accucor/isocor files, the loading script generated an error.

### Steps to reproduce

The data that generates this issue is in the the [`lingfan_albko_fcirc_2022-08` branch](https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/tree/lingfan_albko_fcirc_2022-08/lingfan_albko_fcirc_2022-08) of the `tracebase-rabinowitz-data` repository.

1. `python manage.py load_study ../tracebase-rabinowitz-data/lingfan_albko_fcirc_2022-08/loading.yaml`

The samples in each file are the same, but there are different compounds in each, so there is no conflict.
![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/645128/8882296b-9526-4857-a8be-b8640d0d35d1)
![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/645128/3e2fd840-4992-41f6-b40f-d086955ec004)

### Current behavior

```
/home/lparsons/Documents/projects/tracebase-rabinowitz-data/lingfan_albko_fcirc_2022-08/./20220818_glucose_glycerol_corrected.xlsx: AggregatedErrors Summary (1 errors / 0 warnings):
        EXCEPTION1(ERROR): MSRunAlreadyLoadedOrNotUnique: The following date, researcher, and protocol:
        date: 2022-08-25 00:00:00
        researcher: Lingfan Liang
        protocol: Hilic25min_qe+Mode
for the load of the current accucor/isocorr file: [20220818_glucose_glycerol_corrected.xlsx] contains samples that were also found to be associated with the following previously (or concurrently) loaded accucor/isocorr file(s).
        Conflicting samples in 20220818_glucose_glycerol_corrected.xlsx and 20220818_amino_acids_cor.xlsx with the same date, researcher, and protocol:
                M1_mix1_T150
                M2_mix1_T150
                M3_glycerol_T150
                M4_glycerol_T150
The date, researcher, protocol, and sample name must be unique for each MSRun.  If these are the same samples in each MSRun, change or be sure to indicate the date of the MSRun for each file to resolve the conflict so you can retain unique and consistent sample names for searching.  If these are the same samples and they were scanned in multiple MSRuns on the same date, we currently don't have a database schema to support that, so reach out to a curator to decide how to resolve the issue.  If these are different samples with the same name, notify the curators so they can change the sample names in the sample sheet to match (i.e. they will be saved with modified sample names using a sample name prefix on the command line (--prefix) so that the accucor/isocorr files do not need to be edited).
Scroll up to see tracebacks for each exception printed as it was encountered.
```

### Expected behavior

Since the compounds for the samples are different, the PeakGroups should all be loaded using the same MSRun.

### Suggested Change

A guess at what might fix the issue.  *Pseudocode encouraged.*

### Comment

Any other relevant context or links to what you were working on when you
discovered the problem.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A list of repository items, dependencies, etc, labeled with add, delete, or
change.  One item per line.  (Mostly, this will be a list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### GUI Change description

Describe changes the user will see.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment] 2023-05-18 15:28
This issue is a duplicate of #65 and #609.

**Comment by hepcat72** [comment] 2023-05-18 15:32
#609 came from a comment on a PR and contains a lot of extraneous/unrelated information, but it boils down to differing from #65 by suggesting that a `get_or_create` call be made with all the record data.

Other factors to consider in implementing #65 is:
- Differentiating between already loaded data files and new data
- Differentiating between actual "same" samples and different sampels with the same name
- Changing the exception strategy from catching issues in code prior to the database operations versus catching, interpreting, and repackaging exceptions that come out of the database operations.

**Closed** 2023-06-21 21:51 UTC
Labels: type:bug, reject:duplicate, priority:1-blocking, priority:2-required, component:7-loading
