### ISSUE TITLE
Colorimetric data columns?

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#338] opened 2022-01-13 17:55 UTC
### Feature Inspiration

Generally speaking, I am not a big fan of huge tables of numbers on the web.   It is hard to find patterns, they often timeout, etc.  But _if_ we are going to offer them, perhaps this might enhance their web utility/value?

During the demo, column sorting was employed on diet/treatment and 2 row-spans/classes of numbers were compared (eye/mental processing of numerical values over ~8 rows); I thought it _might_ be nice to have a heat map or colorscale that tracked with normalized labeling, or whatever other numerical attribute was deemed "important".

Related to #157.

### Feature Description

A possible example(s):
https://dotnetgenetics.blogspot.com/2020/10/bootstrap-table-wenzhixin-set-table.html
https://chartio.com/learn/charts/heatmap-complete-guide/

### Alternatives Considered

Background colors on existing data column?
New/adjacent column that only contains the "color equivalent" of the adjacent measurement?
Only offer if rows < than some threshold and a single (or subset of) compound(s)?

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by mneinast** [comment] 2022-01-13 21:42
this would be awesome and go a long way towards improving usability with hopefully less effort to develop compared to a full visualization suite.

In addition to heatmap/color scales, inline horizontal bars could be very useful:
![image](https://user-images.githubusercontent.com/34348153/149413294-6dd42058-102b-4f2f-8a29-1b58051c055d.png)

This is a screenshot from [excel using conditional formatting](https://support.microsoft.com/en-us/office/use-conditional-formatting-to-highlight-information-fed60dfa-1d3f-4e13-9ecb-f1951ff89d7f).

**Comment by hepcat72** [comment] 2024-11-12 22:42
Dupe of #157

**Closed by hepcat72** 2024-11-12 22:42 UTC
Labels: reject:duplicate, type:feature, component:templates, priority:4-low, effort:4-under1day
